### ISSUE TITLE
Project running

### ISSUE THREAD

**Issue by ghost** [runkod/runkod-cli#3]
hello ,

im asking about runing a project on t hosting , i uploaded a files but how to run on platform or i must redirect to root folder !

Cdly

**Comment by talhasch** [comment]
Hey,

Our documentation section will guide you step by step: https://runkod.com/docs

**Comment by talhasch** [comment]
@1FH8scDXoXPzYoaiTtFpL6RYYsDDtHQYR7 can you elaborate "t hosting"?

**Comment by ghost** [comment]
Hello. 
I uploaded the files on ly website staytunne.com . But the hosting dosnt support nodejs or php hosting. 
I fixed the problem from my files  .

Can you clarify which hosting you provide and what the benefit of the project . I really like it 😊
